### ISSUE TITLE
Phenotypes

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/documentation#1]
- [ ] Update metadata
- [ ] homogeinize field names

**Comment by jackeblagare** [comment]
Hi Cyril,

I'm currently looking at the /phenotypes/metadata call as we're attempting to map the calls to our data model. I'm not sure if this has been discussed before but I noticed that germplasm information is a bit redundant. Can't we limit it to just the germplasmPUI? Or maybe that plus the germplasm display name?

Another thing is the observationVariables attribute. Just to confirm, is this just a list of variables or should it include a corresponding value?

**Comment by gcornut** [comment]
Metadata has been deleted. See issue #6
