### ISSUE TITLE
sortOrder in "List Study Summaries"

### ISSUE THREAD

**Issue by GuilhemSempere** [plantbreeding/Documentation#10]
I think this would be better defined as a boolean named sortDesc for instance. That way :
- it wouldn't always need to be specified whenever sortBy is
- we would avoid getting invalid input values

**Comment by jeback1** [comment]
Makes sense. I propose we accept this suggestion.

**Comment by jackeblagare** [comment]
sortOrder is an optional parameter though so there's no need to specify it right?

**Comment by GuilhemSempere** [comment]
It is optional but I would have thought that it "seemlessly" becomes mandatory if sortBy is specified... which I think is not optimal

**Comment by jackeblagare** [comment]
Not necessarily. On the implementation side, there is usually a default ordering already. So for example, if ​**sortBy = studyDbId**​ is specified and sortOrder is not, it could just return a response with studyDbIds sorted in DESC by default or ASC depending on the implementation. I just think that if you have sortDesc, you would need to have sortAsc also.

**Comment by GuilhemSempere** [comment]
Yes I was assuming ASC could be some kind of standard default,, but you're right, in some cases it may not be

**Comment by jeback1** [comment]
Will leave as is.
