### ISSUE TITLE
Save or Update Measurements - transactionDbId

### ISSUE THREAD

**Issue by rhernandezt** [plantbreeding/Documentation#11]
Remove the transactionDbId field in the Save op Update Measurements call, because:

The transactionDbId needs to be generated by the system that is saving or updating the data (the server), NOT by the system that is sending the data (client).

The response of this call should include the transactionDbId, something like this:

{
  "metadata": {
    "status": {
      "message": "The data was updated correctly."
      "transactionDbId" : "9844534"
    }
  }
}

Finally, the client can store the transactionDbId or not.

**Comment by jeback1** [comment]
This makes sense to me.  One suggestion would be to move the data out of the status section:
{
"metadata": {
"status": {
"message": "The data was updated correctly."
}
}
"results":{
    "transactionDbId": "9844534"
}
}

**Comment by nikkicarumba** [comment]
In IRRI, we have a staging area of our operational data called data terminal. Every data sets uploaded in the database refers to a transaction.

The idea behind sending the transactionDbId in the POST/PUT request is to update the data set in the transaction, hence, when you send POST/PUT and the transctionDbId is null, a transactionDbId is created.

Correct, transactionDbId should be in the response and client may save the transactionDbId.

**Comment by jeback1** [comment]
Yes, clearly needed by IRRI.  Update documentation to clearly state purpose of this field.
