### ISSUE TITLE
Definition for /brapi/v1/programs-search is missing

### ISSUE THREAD

**Issue by jackeblagare** [plantbreeding/Documentation#12]
The definition for the /brapi/v1/programs-search call is not yet defined in the documentation.

**Comment by jackeblagare** [comment]
As discussed, we don't include the */programs-search* call yet. We just support filtering by name/abbreviation (exact matches only) as GET parameters for the existing */programs* call.

**Comment by jeback1** [comment]
Would we need a POST method for this? If there was only be one parameter to search, it seems that GET might be sufficient.

**Comment by jeback1** [comment]
For now, no search capability, simply filter on exact match for programName or programAbbrev
