### ISSUE TITLE
Germplasm search: MCPD search by accessionNumber

### ISSUE THREAD

**Issue by guignonv** [plantbreeding/Documentation#13]
We need to be able to (POST) search germplasm by accession number on implementation that supports MCPD.

After the line
"germplasmName" : "XYZ1", // (optional, text, `Triticum, Hordeum`) ... The name or synonym of the accession

we need:

"accessionNumber" : "ITC0906", // (optional, text, 'ITC0906') ... [MCPD] The accession number

**Comment by jeback1** [comment]
Makes sense, I propose we accept this change.

**Comment by jeback1** [comment]
germplasmDbId -- miss-labeled as external identifier

**Comment by gcornut** [comment]
I've created a pull request (plantbreeding/API#8) for this issue. If anyone sees something to add/modify/delete, let me now.
