### ISSUE TITLE
Observation variables by category & crop

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/Documentation#14]
Being able to filter observation variables by crop name would really be handy.

Could we consider merging the "variables" call with the "variables by category" call and get parameters?

Proposed URL:
`[GET] /variables?category={categoryName}&crop={cropName}`

**Comment by jeback1** [comment]
Propose that we follow proposed convention of having crop as part of the url (pre-filtering) and follow Guillaume's suggestion to consolidate the calls.

**Comment by gcornut** [comment]
"varaibles" & "variables by category" have been merged in pull request https://github.com/plantbreeding/API/pull/1
