### ISSUE TITLE
StudyTypeDbId in the Study Type call

### ISSUE THREAD

**Issue by rhernandezt** [plantbreeding/Documentation#16]
Should we consider add the StudyTypeDbId in the response?

Current response: 

{
    "name": "Crossing Nursery",
    "description": "Description for Nursery study type"
}

Proposal response:

{
    "studyTypeDbId" : "2"
    "name": "Crossing Nursery",
    "description": "Description for Nursery study type"
}

**Comment by jackeblagare** [comment]
Maybe this should be in a separate section? I think this is a general call for getting all study types and not the study type for a specific study.

**Comment by rhernandezt** [comment]
The standard in most calls are: DbId , name, and description of the object. This call should implement the same standard as well.

**Comment by jackeblagare** [comment]
Sorry. I missed the *type* word in the studyTypeDbId. You're right. It should be included.

**Comment by jeback1** [comment]
Agree; Will fix.

**Comment by BrapiCoordinatorSelby** [comment]
This issue was moved to plantbreeding/API#222
