### ISSUE TITLE
Identifiers ("dbId" vs "id")

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/Documentation#17]
There are some inconsistencies in the documentation of identifiers
- some call have "dbId", some have "id", some have both!
- some "dbId" are numeric, some are string (in the JSON response or the parameter list) 

I think we all agreed on a string "dbId", right?

I could change the apiary documentation but I don't have the right to modify it

**Comment by rhernandezt** [comment]
Only remember that we are using the lower case camel notation, then, it needs to be "DbId".

**Comment by BrapiCoordinatorSelby** [comment]
V1.1 should have fixed all these inconsistencies. Everything should have the form "xxDbId": "String" 
If you see any specific instances that got missed in the documentation, please open a new issue in the [API](https://github.com/plantbreeding/API/issues) repo
