### ISSUE TITLE
add/update trait/method/scale definitions via BRAPI

### ISSUE THREAD

**Issue by rfinkers** [plantbreeding/Documentation#18]
Currently, there is no means to update / add new observations via the API. Only get. Having such functionality would be useful.

**Comment by jeback1** [comment]
There are a few calls that have an update method.  I suggest that full CRUD should be considered for version 2 but would be more than we would want to take on for version 1.

**Comment by BrapiCoordinatorSelby** [comment]
This issue was moved to plantbreeding/API#221
