### ISSUE TITLE
Rationalize contact in Study Details

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/Documentation#2]
Should we use 
|keyContact|
or 
|contacts|List of contacts| each cantact have a type, name and email||

**Comment by Dave-Matthews** [comment]
For GOBII we probably need a /contacts or /persons call, returning values for keys contactDbID, name, institution, department, email, phone.  The contactDbID would then be used here in Study Details, and instead of leadPerson in the /programs call.

**Comment by rhernandezt** [comment]
Only remember that the "lead" person in most cases is not the same that the "contact" person. Changing the lead person instead of contact person maybe is not the best solution. We should keep the lead person in the program call.

**Comment by jeback1** [comment]
I like the idea of having a common structure associated with contacts that we could use where ever we need contact information.  Do we want to include and optional contactDbId? i.e.
|contacts|list of contacts|[{"contactDbId": string, "contactName": string, "contactType": string, "contactEmail":string}]|

**Comment by cpommier** [comment]
Hi,
Possibly, we could add an optional  orcid.
Best
Cyril 
Le 29 juil. 2016 5:31 PM, jeback1 <notifications@github.com> a écrit :I like the idea of having a common structure associated with contacts that we could use where ever we need contact information.  Do we want to include and optional contactDbId? i.e.
|contacts|list of contacts|[{"contactDbId": string, "contactName": string, "contactType": string, "contactEmail":string}]|

**Comment by jeback1** [comment]
orcid -- standardized way of referring to people, especially as relates to authorship.  Fine with me to add it.

**Comment by jeback1** [comment]
Agreement on proposal, will update calls that contain contact information.

**Comment by naymesh** [comment]
ORCID : (http://orcid.org/)

**Comment by gcornut** [comment]
I've created a pull request for this issue. If anyone sees something to add/modify/delete, let me now.

**Comment by marieALaporte** [comment]
fixed after the merge
