### ISSUE TITLE
matchMethod disappeared from germplasm search call

### ISSUE THREAD

**Issue by nickmorales** [plantbreeding/Documentation#20]

**Comment by jeback1** [comment]
Good catch, I'll look to add it back in.

**Comment by nickmorales** [comment]
previously matchMethod was either 'exact' or 'wildcard', where 'wildcard' allows % or * for multiple character matching and ? for single character matching

**Comment by BrapiCoordinatorSelby** [comment]
closing this issue in favor of [API #193](https://github.com/plantbreeding/API/issues/193)
