### ISSUE TITLE
Metadata with no pagination or status should use null instead of empty objects

### ISSUE THREAD

**Issue by guignonv** [plantbreeding/Documentation#24]
Currently, we use an empty object "{}" for "pagination" or "status" when these are not used. For Java implementers, having an empty object does not make since (while an empty array is ok). So we decided to replace empty objects with "null" value instead. It should be updated in the documentation before freezing.

**Comment by BrapiCoordinatorSelby** [comment]
This issue was moved to plantbreeding/API#218
