### ISSUE TITLE
Genome maps call markerDbId is still an int

### ISSUE THREAD

**Issue by sebastian-raubach** [plantbreeding/Documentation#25]
See title. Should be a String. Call url: /maps/mapDbId/positions

**Comment by gcornut** [comment]
Other calls have the same problem. 
Related issue #17

**Comment by lukasmueller** [comment]
The /maps section seems to be missing from the Github repo...

**Comment by lukasmueller** [comment]
fixed in 087085d26caa124cd931ae0cd4cc492a4227716d.
