### ISSUE TITLE
Get observation unit details as table

### ISSUE THREAD

**Issue by jackeblagare** [plantbreeding/Documentation#26]
I would like to propose that we modify the /brapi/v1/studies/studyId/observationunits call so that it supports a parameter called **table**. If the value of **table** is **TRUE**, the response will be returned in table form.

This is currently available in `/brapi/v1/studies/studyDbId/table` but the structure would make more sense if it's just `/brapi/v1/studies/{studyDbId}/observationunits?table=TRUE`.

CC: @nikkicarumba

**Comment by sebastian-raubach** [comment]
Returning two different Json results (different structure) from the same call isn't good practice.

I'd rather suggest to adopt the flat file return paradigm here, similar to the `/allelematrix-search` call by specifying the `format` parameter. That way, the structure of the Json response is always the same.

**Comment by jackeblagare** [comment]
Agreed. `/brapi/v1/studies/{studyDbId}/observationunits?format=tsv` would be the appropriate call. The `/brapi/v1/studies/studyDbId/table` call needs to bre reviewed.

**Comment by matthewb22** [comment]
The table call is currently in use by the Wagininen Group in their HIDAP implementation. We should escalate the information gathering about which calls are implemented and used in practice now, so we can be careful in reviewing and potentially wholesale rearchitecting calls that are implemented and out in the wild.

Working code is king - an API being used is of real value. Please can we leave this call as it is, and implement a new call for tsv format, if anyone needs it.  We can then deprecate the table call in consultation the Wagininen group in terms of timings and then retire it. If the stats consumers like the table format, however, then we should keep it.

**Comment by jackeblagare** [comment]
I talked to Reinhard and he said it wouldn't be much of a problem as long as the new call has the information currently in the `/table` call. However, if we can't be fully positive that removing the call won't create extra work for those who implemented it already before the release, let's leave it as is.
