### ISSUE TITLE
Study details expand parameter

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/Documentation#27]
Has I understood, one of the API compliance rules was that a JSON response for a specific call shouldn't change (except for arbitrary fields under ```additionalInfo```).

For the study details call ```/brapi/v1/studies/{dbId}```, the ```expand``` parameter can in fact change the JSON response of the call. I would advocate for the removal of this parameter.

In my opinion, we shouldn't expand fields that could get too big. The ```location``` field would be fine but not ```layout```, ```germplasm```, ```observationVariables``` or ```observationUnits``` because they could produce huge JSON objects.
To get these, we would then need to use the specific calls for germplasm, observation variables, layout, etc. 

Any opinions on the matter?

Proposed JSON response:
```json
{
  "metadata": {
    "pagination": null,
    "status": null,
    "datafiles": []
  },
  "result": {
    "studyDbId": 35,
    "studyName": "Earlygenerationtesting",
    "studyType": "Yield study",
    "seasons": [
      "2005 Winter",
      "2008 Summer"
    ],
    "trialDbId": 57,
    "trialName": "International Yield Trial",
    "startDate": "2005-06-01",
    "endDate": "2008-12-31",
    "active": "true",
    "location": {
        "locationDbId": 1,
        "locationType": "Study location",
        "name": "Ibadan",
        "abbreviation": "IB",
        "countryCode": "NGA",
        "countryName": "Nigeria",
        "latitude": -21.5,
        "longitude": 165.5,
        "altitude": 12,
        "additionalInfo": {
          "AnnualMeanRain": "value",
          "SoilDescription": "23",
          "property1Name": "property1Value",
          "property2Name": "property2Value"
        }
    },
    "additionalInfo": {
      "studyObjective": "Increase yield",
      "principalInvestigator": "Dr. Breeder",
      "property1Name": "property1Value",
      "property2Name": "property2Value",
      "property3Name": "property3Value"
    }
  }
}
```

**Comment by lukasmueller** [comment]
I agree that it would make it conceptually simpler and clearer… maybe easier to write software against it also.

cheers
Lukas

**Comment by gcornut** [comment]
I've made a [pull request](https://github.com/plantbreeding/API/issues/2) following my proposition
Here is the [proposed study details](https://github.com/plantbreeding/API/blob/api-compliance-study-details/Specification/Studies/StudyDetails.md)

If anyone has an opinion against or if anyone has some comment I can modify the pull request accordingly.

**Comment by matthewb22** [comment]
Please check with the IRRI group - the reason the expansion parameter was included was to accomodate their wish to consume the information for handheld devices in a single call

I agree to componentise and assemble thorugh embedded links and separate calls is safer, but it was their particular wish.

I propose we keep the original - if the response size is too large perhaps we should find a way to handle that situation so the consuming client can react.

**Comment by gcornut** [comment]
I agree we need more feedback for this issue.

@jackeblagare @araquel @nikkicarumba Can you remind us what requirement the IRRI's information system has for the study details?

My idea here was to simplify this call to the minimum required fields with consistent response object.
I understand having ```germplasm```, ```observationVariables``` and ```layout``` all in one batch could be useful but the ```observationUnits``` field seems out of place to me.

**Comment by jackeblagare** [comment]
Hi @gcornut, we were discussing this issue and we agreed that the expand parameter will cause inconsistencies with the responses. 

We can manage without the expand parameter.

**Comment by gcornut** [comment]
Ok good. And so, what fields do you need in the study details?

Do you think getting the `germplasm`, `observationVariables`, `layout` and `observationUnits` from other BrAPI calls would be a problem for your use case?

The corresponding calls are:
- `[GET] /studies/{studyDbId}/germplasm`
- `[GET] /studies/{studyDbId}/observationVariables`
- `[GET] /studies/{studyDbId}/layout`
- `[GET] /studies/{studyDbId}/observationUnits`

**Comment by lukasmueller** [comment]
Are there any more opinions on this matter? Otherwise I am going to merge!

**Comment by gcornut** [comment]
I guess we can close this issue since the pull request was merged.

It can still be re-opened if needed
