### ISSUE TITLE
germplasmDbId parameter in Markerprofile data

### ISSUE THREAD

**Issue by lmansueto** [plantbreeding/Documentation#28]
It is already defined that markerprofile is defined for a germplasm and/or study and/or sample and/or extract. But in the call /brapi/v1/markerprofiles/germplasmDbId , it is assigned only to a germplasm? shouldn't this be markerProfileId?

**Comment by sebastian-raubach** [comment]
I agree, this should be the `markerprofileDbId`. That's how we implemented it in Germinate anyway.

Don't know why it uses the `germplasmDbId` in the docs.

**Comment by lukasmueller** [comment]
Fixed in 482181412f1595da7715f4b9410cde6eeff4b58a.
