### ISSUE TITLE
Observation variable ontologies

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/Documentation#29]
We are currently developing the next version of our JavaScript [trait ontology widget](https://github.com/cpommier/trait-ontology-widget) that will consume the breeding API observation variables.

For this use case, we need to fetch all the ontologies of a breeding API server with additional metadata (ontology version, authors, licence, etc.). Currently, the only way to list ontologies is to **load all** the variables and extract the ontology identifiers and names.

In consequence, we'd like to propose the following call:
## Ontology list 
Request: [GET] ```/brapi/v1/ontologies?page={page}&pageSize={pageSize}```
Response : 
```json
{
  "metadata": {
    "pagination": {
          "pageSize": 2,
          "currentPage": 1,
          "totalCount": 300,
          "totalPages": 100
      },
      "status": null,
      "datafiles": []
  },
  "result": {
    "data": [{
      "ontologyDbId": "CO_334",
      "ontologyName": "Wheat ontology",
      "authors": "J. Snow, H. Peterson",
      "version": "v1.2",
      "copyright": "© 2016, INRA",
      "licence": "CC BY-SA 4.0"
    },{
      "ontologyDbId": "CO_335",
      "ontologyName": "Rice ontology",
      "authors": "J. Doe",
      "version": "v2",
      "copyright": null,
      "licence": null
    }]
  }
}
```
---
We understand that additions to **V1** should be avoided and we could report this to **V2**. But then our widget would implement the breeding API **V2** directly.

**Comment by matthewb22** [comment]
We need to draw the line on versions as there will always be new calls required. I see no harm in making this a provisional call for V2 and I see no harm for your group to implement V2 directly or better implement V1, plus a single V2 call, as the URLs are clearly distinguishing. The only danger you will face is that this V2 call may be refined over time until V2 is sealed, but if you are development the client that should be easy to adjust.

It is my understanding that V1 has now been delivered and I support that - but I will of course defer to Jan Erik and Lukas if the timelines have changed.

**Comment by rfinkers** [comment]
Agree with @matthewb22 on his view.

**Comment by lukasmueller** [comment]
Seems to me that this is an important call that we should include in V1…

cheers
Lukas

**Comment by matthewb22** [comment]
Very happy to defer @lukasmueller and include it. Let's go ahead.

**Comment by gcornut** [comment]
Ok I've created a pull request (plantbreeding/API#3) that adds this call into the breeding API.

Of course I can still modify it if anyone sees an error or something missing before it is merged.
