### ISSUE TITLE
/variables and /variables-search harmonisation

### ISSUE THREAD

**Issue by cpommier** [plantbreeding/Documentation#31]
The parameter /brapi/v1/variables?category={categoryName} allows to search all phenological or physiological traits accross several ontologies. It uses the trait.class filed of the returned json.

This seems redundant with /brapi/v1/variables-search?class=phenology
The solution might be to remove /variables?category and keep only /variables and /variables-search

Also we should document /variables-search and add an exemple of class (renamed as traitClasses forclarity) : 
"traitClasses" : ["phenology", "physiological trait"]

Bonus:
Missing pagination parameters on /variables and /variable-search

**Comment by gcornut** [comment]
@lukasmueller I can prepare a pull request if you want so everyone can better see the modifications this issue implies

**Comment by marieALaporte** [comment]
This issue was moved to plantbreeding/API#34
