### ISSUE TITLE
list study summaries and study search both use same url

### ISSUE THREAD

**Issue by nickmorales** [plantbreeding/Documentation#36]
http://docs.brapi.apiary.io/#reference/study/list-study-summaries/search-studies
http://docs.brapi.apiary.io/#reference/study/search-studies/search-studies

Both calls use /brapi/v1/studies-search
Maybe these two can be consolidated?

**Comment by jackeblagare** [comment]
Yes. They're the same just categorized according to use case but then we're defining the calls not the possible use cases.

**Comment by gcornut** [comment]
The list study summaries was meant to be a GET request and the search study is a POST request.

I'm not against removing the study summary list GET request, we only use the study search POST request.

**Comment by mverouden** [comment]
Please do not remove the GET request for study summary list, it is very important for Reinhard and me. This call is the workhorse for my work in doing statistical analyses on field trial data.

**Comment by marieALaporte** [comment]
This issue was moved to plantbreeding/API#33
