### ISSUE TITLE
pagination starts at 1 on the germplasm search call example

### ISSUE THREAD

**Issue by marieALaporte** [plantbreeding/Documentation#38]
current page should be 0 as there is only one page.

**Comment by marieALaporte** [comment]
same for the following examples:
List attribute categories
Germplasm attribute values by germplasmDbId
Markerprofile search
Markerprofile data
MarkerProfile Allele Matrix
Program list
List Seasons
List Study Types
Study Observation Variables
Study Germplasm Details
List Observation Levels
Observation Unit Details
Study Observation Units as a Table
Plot Layout Details
Get Observation Units by observation variable ids
Phenotype Search
Variable data type list

**Comment by lukasmueller** [comment]
fixed in 358d00b51f90f5808ad3408842fae250c395d1d3
