### ISSUE TITLE
Authorization Code Request for brAPI Authentication (OAuth2)

### ISSUE THREAD

**Issue by jackeblagare** [plantbreeding/Documentation#39]
One of the processes in OAuth2 is retrieving an authorization code which will be exchanged for an access token. At the moment, this is not part of the specifications. If OAuth2 support is to be added in the future, this should be considered also.

Since our implementation requires this process, we had to implement an endpoint prior to the /token brAPI call.

**Comment by BrapiCoordinatorSelby** [comment]
This issue was moved to plantbreeding/API#216
