### ISSUE TITLE
/phenotypes/hierarchical call has unknown use case, duplicate function, and no implementation

### ISSUE THREAD

**Issue by lukasmueller** [plantbreeding/Documentation#5]
The `/phenotypes/hierarchical` call is very similar to the `/phenotypes` call. After discussion in the phenotypes breakout group, suggestion to remove this call from the API.

**Comment by lukasmueller** [comment]
The call was removed from the API. Below a copy for reference.

## Phenotypes hierarchical, study agregated, dataset  [/brapi/v1/phenotypes/hierarchical?observationUnitLevel=plot&studyDbId=876&treatmentFactor=lowInput&germplasmGenus=&germplasmDbId&germplasmPUI=http://data.inra.fr/accession/234Col342&germplasmSpecies=Triticum&panel=diversitypanel1&collection=none&observationVariables=CO_321:000034,CO_321:000025&location=bergheim&season=2005,2006&pageSize={pageSize}&page={page}]
Scope: PHENOTYPING.
Status: RECOMMENDED FOR DEPRECECATION. THIS PROVIDES FUNCTIONALITY THAT IS A DUPLICATE OF studies CALLS.
### Phenotypes/hierarchical [GET]

A variation of the above return type with a factorisation of the study information from observationUnits to study.

location : first find all the studies for your location search parameter then inject this list of studyIds 
We probably need a better handling of the list of possible values.
In the response, note that trait ids can either be ontology ids or PUI. 

Consider using Json LD to handle locale, for V2.
instanceNumber : For data colleciton, nullable
season : phenotypingCampaignName
observationTimeStamp : Iso Standard
observationValue data type inferred from the ontology 


+ Parameters
    + germplasmPUI (optional, text, `http://data.inra.fr/accession/234Col342`) ... The name or synonym of external genebank accession identifier
    + germplasmDbId (optional, text, `986`) ... The name or synonym of external genebank accession identifier
    + germplasmSpecies (optional, text, `Aegilops taushi`) ... The name or synonym of genus or species ( merge with below ?)
    + germplasmGenus (optional, text, `Triticum, Hordeum`) ... The name or synonym of genus or species
    + panel (optional, text, `breedingProgramPanel2011`) ... The name of a specific panel 
    + collection (optional, text, `BRCCollection_Wheat`) ... The name of a specific Collection    
    + observationVariables (optional, text, `CO_321:00000234`) ... The IDs of traits, could be ontology ID, database ID or PUI
    + studyDbId (optional, text, `2356`) ... The database ID / PK of the studies search parameter
    + season (optional, text, `2001`) ... The year or Phenotyping campaign of a multiannual study (trees, grape, ...)
    + treatmentFactor (optional, text, `water regimen`) ... The environment, cultural practice applied to the study subjects.
    + observationUnitLevel (optional, text, `plot`) ... The type of the observationUnit. Returns only the observaton unit of the specified type; the parent levels ID can be accessed through observationUnitStructure.
    

+ Response 200 (application/json)

        {
            "metadata": {
                "pagination": {
                    "pageSize": 10,
                    "currentPage": 1,
                    "totalCount": 10,
                    "totalPages": 1
                },
                "status": [],
                "datafiles": []
            },
            
            "result" : [
                {
                    "studyId": "RIGW1",
                    "studyLocation": "Bergheim",
                    "studyPUI": "http://phenome-fppn.fr/maugio/2345",
                    "observationUnitLevelTypes" : [ "plant","plot", "bloc"],
                    "observationUnits" : 
                    [
                        {
                            "germplasmPUI": "http://inra.fr/vassal/41207Col0001E",
                            "germplasmDbId": 3425,
                            "germplasmDisplayName": "charger",
                            "observatioUnitDbId": 20,
                            "observationUnitPUI": "http://phenome-fppn.fr/maugio/bloc/12/2345",
                            "treatments": 
                            [
                                {
                                    "factor" : "water regimen" ,
                                    "modality":"water deficit"
                                },
                            ]
                            "observationUnitLevelLabels": [ "1","26123", "1"]
                            "attributes": 
                            [
                                {"att1" :"value"}, 
                                {"numPot" :"23"}
                            ] 
                            "X" : "",
                            "Y" : "",
                            "XLabel" : "", 
                            "YLabel" : "", 
                            "data": 
                            [
                                {
                                    "instanceNumber" : 1,
                                    "observationVariableId": "CO_321:0000045", 
                                    "observationVariableDbId": 35, 
                                    "season": "2005", 
                                    "observationValue" : "", 
                                    "observationTimeStamp": null,
                                    "quality": "reliability of the observation",
                                    "collectionFacilityLabel": "phenodyne",
                                    "collector" : "userURIOrName"
                                },
                                {
                                    "instanceNumber" : 1,
                                    "observationVariableId": "http://www.cropontology.org/rdf/CO_321:0000025", 
                                    "observationVariableDbId": 35, 
                                    "season": null,
                                    "observationValue" :  32,
                                    "observationTimeStamp": "2006-07-03::10:00",
                                    "quality": "8",
                                    "collectionFacilityLabel": null,
                                    "collector" : "userURIOrName"
                                }
                            ]
                        }
                    ]
                }
            ]    
        }



# Group Traits

API to retrieve list of traits and their associated variables


## Traits [/brapi/v1/traits]
Scope: CORE.
Status: IN DISCUSSION.

Call to retrieve a list of traits available in the system and their associated variables.

### List all traits [GET]
+ Response 200 (application/json)
    
        {
            "metadata" : {
                "pagination" : {    
                    "pageSize": 3, 
                    "currentPage": 1, 
                    "totalCount": 300, 
                    "totalPages": 100 
                }
                "status" : [],
                "datafiles": []
            },
        
            "result" : {
                "data" : [
                    {
                        "traitDbId": "123",
                        "traitId": "CO:123000007",
                        "name": "Plant Height",
                        "description": "Description of Plant Height",
                        "observationVariables": [
                            "CO_334:0100121", 
                            "CO_334:0100122", 
                            "CO_334:0100123" 
                        ],
                        "defaultValue": null
                    },
                    {
                        "traitDbId": "123",
                        "traitId": "CO_334:0100620",
                        "name": "Carotenoid content",
                        "description": "Cassava storage root pulp carotenoid content",
                        "observationVariables": [
                            "CO_334:0100621", 
                            "CO_334:0100622", 
                            "CO_334:0100623" 
                        ],
                        "defaultValue": null
                    }
                ],

            ]
        }

**Comment by jeback1** [comment]
No objections when reviewed.
