### ISSUE TITLE
Harmonizing the /phenotypes call with the rest of the API

### ISSUE THREAD

**Issue by lukasmueller** [plantbreeding/Documentation#6]
The phenotypes call seems to contain parameters that are named differently than in the rest of the API.

**Comment by lukasmueller** [comment]
Parameter list:
* The parameter list should be restructured to be a json data structure, similar to the /studies [POST] call.

germplasmPUI should not be a search parameter, use germplasmDbId

**Comment by gcornut** [comment]
Linked to #3

**Comment by jackeblagare** [comment]
@lukasmueller, I mentioned to the group the issue of having **[POST] /studies** as an advanced searching call for the studies resource. It's not difficult to mistake it as a call to create a new study. This applies to other resources as well.

**Comment by lukasmueller** [comment]
Good comment Jack... we should discuss this in the group!!!!

**Comment by gcornut** [comment]
Decision made on issue #9

**Comment by jeback1** [comment]
Call has been updated.
