### ISSUE TITLE
Use ObservationSet call not clear

### ISSUE THREAD

**Issue by lukasmueller** [plantbreeding/Documentation#7]
The use of the observationSet call was not clear to people at the hackathon. It was removed from apiary and a copy is given here.

# Group Observation Set

API calls for retrieving observation sets and measurement data.

### List all observation sets [GET]

+ Parameters
    + id (optional,numeric) - unique identifier for the observation set
    + name (optional,string) - human-readable name for the observation set
    + species (optional,string) - species. This could be a set of comma-separated values.
    + program (optional,string) - the program the observation set belongs to. This could be a set of comma-separated values.
    + year (optional,numeric) - the year the observation set was created. This could be a set of comma-separated values.
    + location (optional,string) - location
    + observationSetType (optional,string) - the type of the observation set.
    + observationUnitType (optional,string) - the type of observation unit under the observation set to be returned. This could be entry, plot,etc.
+ Response 200 (application/json)

        {
            "metadata": {},
            "result": {
                "observationSetId": "11",
                "observationSetUri": "x.x.x/v1/observationSets/11",
                "observationSetName": "Human readable name",
                "species": [
                    {
                        "speciesName": "speciesName",
                        "speciesUri": "x.x.x/v1/species/1"
                    }
                ],
                "program": [
                    {
                        "programName": "programName",
                        "programUri": "x.x.x/v1/programs/1"
                    }
                ],
                "year": [
                    "2013",
                    "2014",
                    "2015"
                ],
                "location": [
                    {
                        "locationName": "locationName",
                        "locationNameUri": "x.x.x/v1/locations/1"
                    }
                ],
                "observationSetType": "controlled vocabulary",
                "metadata": {
                    "description": "this is a parent list",
                    "author": "URL to user"
                },
                "observationData": [
                    {
                        "HARVEST_DATE": {
                            "observationVariableUri": "x.x.x/v1/observationVariables/123",
                            "value": "2015-06-16",
                            "timestamp": "",
                            "remarks": ""
                        }
                    }
                ],
                "childrenDatasets": [
                    {
                        "observationUnitId": "17778",
                        "observationUnitTypeUri": "x.x.x/v1/observationUnitTypes/123",
                        "parentObservationSetUri": "x.x.x/v1/observationSets/11",
                        "parentObservationUnitUri": null,
                        "germplasmDbId": "x.x.x/v1/germplasm/145",
                        "metadata": {
                            "entryName": "IR 64",
                            "entryNumber": "1"
                        },
                        "observationData": [
                            {
                                "PLANT_HEIGHT_AVG": {
                                    "observationVariableUri": "x.x.x/v1/observationVariables/123",
                                    "value": "xxx",
                                    "timestamp": "",
                                    "remarks": ""
                                }
                            }
                        ]
                    },
                    {
                        "observationUnitId": "17779",
                        "observationUnitTypeUri": "x.x.x/v1/observationUnitTypes/15",
                        "parentObservationUnitUri": "x.x.x/v1/observationSets/17778",
                        "germplasmDbId": "x.x.x/v1/germplasm/145",
                        "metadata": {
                            "plotNo": "1",
                            "rep": "1"
                        },
                        "observationData": [
                            {
                                "PLANT_HEIGHT_1": {
                                    "observationVariableUri": "x.x.x/v1/observationVariables/129",
                                    "observationUnitTypeUri": "x.x.x/v1/observationUnitTypes/15",
                                    "value": "xxx",
                                    "timestamp": "",
                                    "remarks": ""
                                }
                            }
                        ]
                    },
                    {
                        "observationUnitId": "17780",
                        "parentObservationUnitUri": "x.x.x/v1/observationSets/17778",
                        "germplasmDbId": "x.x.x/v1/germplasm/145",
                        "metadata": {
                            "plotNo": "1",
                            "rep": "2"
                        },
                        "observationData": [
                            {
                                "PLANT_HEIGHT_2": {
                                    "observationVariableUri": "x.x.x/v1/observationVariables/129",
                                    "observationUnitTypeUri": "x.x.x/v1/observationUnitTypes/15",
                                    "value": "xxx",
                                    "timestamp": "",
                                    "remarks": ""
                                }
                            }
                        ]
                    }
                ]
            }
        }

**Comment by jeback1** [comment]
No objections were raised during review.
